### ISSUE TITLE
Running robot framework tests inside a container is causing ResponseError: 5000: Unclassified error [null]

### ISSUE THREAD

**Issue by moijes12** [reportportal/client-Python#37]
I am facing an issue where I am unable to publish my test results to report portal and I suspect it could be because of networking. Below is a more detailed view of my problem.

### Test Setup
* Tests are running inside a ubuntu image on a gitlab-runner container , say **hostname gitlab.network**
* The reportportal server is running on a different host, say **report-portal.network**
* The tests are called in the docker container with the below command:
```
robot -d reports --pythonpath lib --variablefile 'variables/config.py' --variable BROWSER:'headlessfirefox' --variable DI_URL:'http://localhost:3000' --listener robotframework_reportportal.listener --variable RP_ENDPOINT:"http://report-portal.network:8080" --variable RP_UUID:"XXXXX-XXXX-XXXX-XXXX-XXXXXXXX" --variable RP_LAUNCH:"GitLab Demo" --variable RP_PROJECT:"GITLAB_TEST" tests/
```

### Issue
As each step is executed, I see the below log writing:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service_async.py", line 208, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 199, in finish_test_item
    return _get_msg(r)
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])
ResponseError: 5000: Unclassified error [null]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service_async.py", line 208, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 199, in finish_test_item
    return _get_msg(r)
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])
ResponseError: 40022: Finish test item is not allowed. Test item '5bc5c17442eba400010da6be' has descendants with 'IN_PROGRESS' status. All descendants '[XvfbRobot.Start Virtual Display (1920, 1080)]'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service_async.py", line 208, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 199, in finish_test_item
    return _get_msg(r)
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/usr/local/lib/python2.7/dist-packages/reportportal_client/service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])
ResponseError: 40022: Finish test item is not allowed. Test item '5bc5c17442eba400010da6bd' has descendants with 'IN_PROGRESS' status. All descendants '[login.Open Headless Browser (), XvfbRobot.Start Virtual Display (1920, 1080)]'
T
```

I am not really sure why this should occur. How can we work together to fix this ? Can I provide you with more information or logs ?

**Comment by alexforever86** [comment]
I'm having the same issue. I'm simply running the example script. Getting the same error log.

**Comment by alexforever86** [comment]
The project or launch name values were incorrect. The error log here is completely misleading.

**Comment by iivanou** [comment]
@alexforever86 We can't check the values of launch and/or a project on Python client's side. The error message you see at the stack trace is being returned by the ReportPortal API. You can create a feature request for the RP API in order to make it return something specific rather than just unclassified error.
