### ISSUE TITLE
robotframework and reportportal v5 reporting failing to get launch_id

### ISSUE THREAD

**Issue by terminal-illness** [reportportal/client-Python#66]
I did some debugging and it looks like start_launch, start_test_item, finish_test_item throw 400 responses when using reportportal_client to report to version 5 of reportportal. I can see in the url  is going to api/v1. Not sure if there is a param to pass to tell the client lib its reporting to v5. 
Changing the api/v2 doesn't help either. Looks like its failing to get the launch_id.
File "**************\venv\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 160, in start_launch
    self.launch_id = _get_id(r)
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 55, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.]
**************\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "**************\venv\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 223, in start_test_item
    item_id = _get_id(r)
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 55, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Incorrect Request. [Field 'launchUuid' should not be null.]
Traceback (most recent call last):
  File "*************\venv\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "****************\venv\lib\site-packages\reportportal_client\service.py", line 223, in start_test_item
    item_id = _get_id(r)
  File "***************\venv\lib\site-packages\reportportal_client\service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "**************\venv\lib\site-packages\reportportal_client\service.py", line 55, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Incorrect Request. [Field 'launchUuid' should not be null.]
**************\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
****************\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
**********\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
******\venv\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
...******************
<Response [201]>
******************
Traceback (most recent call last):
  File "****\venv\lib\site-packages\reportportal_client\service_async.py", line 233, in process_item
    self._post_log_batch()
  File "****\venv\lib\site-packages\reportportal_client\service_async.py", line 203, in _post_log_batch
    self.rp_client.log_batch(self.log_batch)
  File "*****\venv\lib\site-packages\reportportal_client\service.py", line 335, in log_batch
    return _get_data(r)
  File "***\venv\lib\site-packages\reportportal_client\service.py", line 58, in _get_data
    "\n  - ".join(["Multiple errors:"] + error_messages))
reportportal_client.errors.ResponseError: Multiple errors:
  - NullPointerException:
  - NullPointerException:
  - NullPointerException:
%%%%%%%%%%%%%%

**Comment by iivanou** [comment]
@terminal-illness Currently, RP version 5 is not supported by Python agents.

**Comment by terminal-illness** [comment]
Ah cool thanks, will it be supported anytime soon? I see the RP team have v5 in master.

**Comment by iivanou** [comment]
Yeah, we will update the client soon.

**Comment by terminal-illness** [comment]
Awesome thanks, please shout if you would like any assistance with testing. Should I close? or we leave it here until the update in case other guys having similar issues?

**Comment by iivanou** [comment]
Let's keep it for now.

**Comment by iamtech123** [comment]
<<I can help you for any testing required>>

I am facing below error while executing Robot framework test case (similar to @terminal-illness )

Command: robot --listener robotframework_reportportal.listener --variable RP_UUID:"UUID" --variable RP_ENDPOINT:"http://IP:8080" --variable RP_LAUNCH:"superadmin_TEST_EXAMPLE" --variable RP_PROJECT:"superadmin_personal" F:\Program\Robot\RF_Sample.robot

Error: 
==============================================================================
RF Sample
==============================================================================
The user can search for flights
DevTools listening on ws://127.0.0.1:<port>/devtools/browser/xx
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 153, in start_launch
    self.launch_id = _get_id(r)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 52, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.]
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 211, in start_test_item
    item_id = _get_id(r)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 52, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Incorrect Request. [Field 'launchUuid' should not be null.]
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 211, in start_test_item
    item_id = _get_id(r)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 32, in _get_id
    return _get_data(response)["id"]
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 52, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Incorrect Request. [Field 'launchUuid' should not be null.]
The user can search for flights                                       | PASS |
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 233, in process_item
    self._post_log_batch()
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 203, in _post_log_batch
    self.rp_client.log_batch(self.log_batch)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 317, in log_batch
    return _get_data(r)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 54, in _get_data
    raise ResponseError(
reportportal_client.errors.ResponseError: Multiple errors:
  - ReportPortalException: Launch 'null' not found. Did you use correct Launch ID?
  - ReportPortalException: Launch 'null' not found. Did you use correct Launch ID?
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 231, in finish_test_item
    return _get_msg(r)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 40, in _get_msg
    return _get_data(response)["msg"]
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 52, in _get_data
    raise ResponseError(error_messages[0])
reportportal_client.errors.ResponseError: Test Item 'None' not found. Did you use correct Test Item ID?
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\reportportal_client\service_async.py", line 234, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 170, in finish_launch
    return self._finalize_launch(end_time=end_time, action="finish",
  File "c:\python38\lib\site-packages\reportportal_client\service.py", line 165, in _finalize_launch
    self.stack.pop()
IndexError: pop from empty list
RF Sample                                                             | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed

Reportportal V5

Python and Robot Framework setup setup
Python : 3.8

Package                         Version
------------------------------- -----------
certifi                         2019.11.28
chardet                         3.0.4
idna                            2.9
numpy                           1.18.1
Pillow                          7.0.0
pip                             19.2.3
Pygments                        2.5.2
Pypubsub                        4.0.3
pywin32                         227
reportportal-client             3.2.3
requests                        2.23.0
robotframework                  3.1.2
robotframework-reportportal     3.1.0
robotframework-ride             1.7.4.1
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  4.3.0
selenium                        3.141.0
setuptools                      41.2.0
six                             1.14.0
urllib3                         1.25.8
wxPython                        4.0.7.post2

**Comment by iivanou** [comment]
@iamtech123 RP version 5 is not currently supported by the agent.

**Comment by iamtech123** [comment]
@iivanou Thanks for the update. I can help you on any testing requirements.

**Comment by iamtech123** [comment]
Now i am able to run the robot test cases with V5. Thank you very much for the support.

**Comment by iivanou** [comment]
@iamtech123 You are welcome!
