### ISSUE TITLE
Getting ImportError while Importing ReportPortalServiceAsync

### ISSUE THREAD

**Issue by vipin3699** [reportportal/client-Python#76]
I am using a reportportal_client to send data to my reportportal.
But when I install reportportal_client and import ReportPortalServiceAsync it through me import error.
Here are the steps I did in my system:-
```
[root@vm138 Jenkins]# virtualenv -p /usr/bin/python2.7 report_test_env
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/workspace/hardware_gui/Spicegate_Hardware_RHEL8_CERT_Stage/spicegate/Jenkins/report_test_env/bin/python2.7
Not overwriting existing python script /home/workspace/hardware_gui/Spicegate_Hardware_RHEL8_CERT_Stage/spicegate/Jenkins/report_test_env/bin/python (you must use /home/workspace/hardware_gui/Spicegate_Hardware_RHEL8_CERT_Stage/spicegate/Jenkins/report_test_env/bin/python2.7)
Installing setuptools, pip, wheel...done.
[root@vm138 Jenkins]# source report_test_env/bin/activate
(report_test_env) [root@vm138 Jenkins]# pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package    Version
---------- -------
pip        20.0.2 
setuptools 44.0.0 
wheel      0.34.2 
(report_test_env) [root@vm138 Jenkins]# pip install reportportal-client
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting reportportal-client
  Using cached reportportal_client-5.0.1-py2.py3-none-any.whl (10 kB)
Collecting requests>=2.4.2
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Installing collected packages: certifi, urllib3, idna, chardet, requests, six, reportportal-client
Successfully installed certifi-2019.11.28 chardet-3.0.4 idna-2.9 reportportal-client-5.0.1 requests-2.23.0 six-1.14.0 urllib3-1.25.8
(report_test_env) [root@vm138 Jenkins]# pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package             Version   
------------------- ----------
certifi             2019.11.28
chardet             3.0.4     
idna                2.9       
pip                 20.0.2    
reportportal-client 5.0.1     
requests            2.23.0    
setuptools          44.0.0    
six                 1.14.0    
urllib3             1.25.8    
wheel               0.34.2    
(report_test_env) [root@vm138 Jenkins]# python
Python 2.7.5 (default, May  3 2017, 07:55:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from reportportal_client import ReportPortalServiceAsync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ReportPortalServiceAsync
>>> from reportportal_client import ReportPortalServiceAsync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ReportPortalServiceAsync
```

Steps to reproduce:-
Create a new virtual environment
`virtualenv -p /usr/bin/python2.7 report_test_env`
activate reportportal-client and run pip list to verify that there should no other packages
`pip list`
install reportportal-client
`pip install reportportal-client`
and try to import ReportPortalServiceAsync
```
(report_test_env) [root@vm138 Jenkins]# python
Python 2.7.5 (default, May  3 2017, 07:55:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from reportportal_client import ReportPortalServiceAsync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ReportPortalServiceAsync
```
I just checked It's working fine till version [3.2.3](https://pypi.org/project/reportportal-client/3.2.3/).

**Comment by iivanou** [comment]
@vipin3699 Could you please read through the [installation](https://github.com/reportportal/client-Python#installation) part of the README? If you report to RPv4, you should not install the latest version of the client.

**Comment by vipin3699** [comment]
Okay I just checked that, My bed I don't know which reportportal version my team is using I was just looking into the python script to send data and that was failing with the above error, Now I got the exact reason of that.
Thanks for instant response :+1:
