### ISSUE TITLE
start_launch failing on RPv4

### ISSUE THREAD

**Issue by Dannyb48** [reportportal/client-Python#78]
We are having an issue using a tool we wrote that uses the reportportal-client to interact with our ReportPortal instance. The issue specifically is calling the `start_launch` method against Report Portal v4.x the error has usually been some form of the following below.

We were able to determine with these latest releases of the client that it's hard-coded to use the v2 API for `start_launch` but RPv4 does not have that V2 APIs. We were able to workaround this by downgrading the client to 3.2.3

Any chance we can make the API version selection configurable? Make it an option passed to the` ReportPortalService` class?

```
Traceback (most recent call last):
  File "/home/dbaez/.virtualenvs/rp_preproc/bin/rp_preproc", line 8, in <module>
    sys.exit(main())
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/rp_preproc/main.py", line 159, in main
    return_code = run(args)
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/rp_preproc/main.py", line 91, in run
    rp_response = preproc.process()
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/rp_preproc/libs/preproc.py", line 130, in process
    response = xunit_xml.process()
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/rp_preproc/libs/xunit_xml.py", line 57, in process
    launch_id = launch.start()
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/rp_preproc/libs/reportportal.py", line 380, in start
    description=self.description)
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/reportportal_client/service.py", line 174, in start_launch
    self.launch_id = _get_id(r)
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/reportportal_client/service.py", line 46, in _get_id
    return _get_data(response)["id"]
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/reportportal_client/service.py", line 61, in _get_data
    data = _get_json(response)
  File "/home/dbaez/.virtualenvs/rp_preproc/lib/python3.6/site-packages/reportportal_client/service.py", line 86, in _get_json
    "Invalid response: {0}: {1}".format(value_error, response.text))
reportportal_client.errors.ResponseError: Invalid response: Expecting value: line 1 column 1 (char 0): <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
        href="./img/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">

    <title>Report Portal - Page 404</title>
</head>
<body>
```
or
```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/reportportal_client/service.py", line 32, in _get_id
    return _get_data(response)["id"]
KeyError: 'id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/app-root/src/rp_preproc/api/process/endpoints/process_payload.py", line 53, in post
    response = preproc.process()
  File "/opt/app-root/src/rp_preproc/libs/preproc.py", line 130, in process
    response = xunit_xml.process()
  File "/opt/app-root/src/rp_preproc/libs/xunit_xml.py", line 57, in process
    launch_id = launch.start()
  File "/opt/app-root/src/rp_preproc/libs/reportportal.py", line 380, in start
    description=self.description)
  File "/opt/app-root/lib/python3.6/site-packages/reportportal_client/service.py", line 153, in start_launch
    self.launch_id = _get_id(r)
  File "/opt/app-root/lib/python3.6/site-packages/reportportal_client/service.py", line 35, in _get_id
    "No 'id' in response: {0}".format(response.text))
reportportal_client.errors.EntryCreatedError: No 'id' in response: {"content":[],"page":{"number":1,"size":20,"totalElements":0,"totalPages":0}}
```

**Comment by iivanou** [comment]
@Dannyb48 Well, we were not planning to make any enhancement in the client regarding RPv4. I suggest you upgrade RP to version 5 'cause the development of the 4th branch has completed. @DzmitryHumianiuk Correct me if I'm wrong.

**Comment by DzmitryHumianiuk** [comment]
v4 finalized.
But we can do complementary fixes

**Comment by Dannyb48** [comment]
@DzmitryHumianiuk @iivanou sorry about that I didn't realize that it was documented. I just noticed it now.

We've fixed it on our end by limiting the version in our setup file to install client 3.2.3 so we can talk to our Production RPv4 instances. 

We are in the middle of standing up a RPv5 instances to test against in house but we just haven't gotten there yet. 

It would be nice to have single client that can toggle talking between the different API versions but I think we can figure out clever ways to workaround this so our tool can be compatible with both RP4/RP5.

You can close this.
